import { ExecArgs } from "@medusajs/framework/types"
import { ContainerRegistrationKeys } from "@medusajs/framework/utils"

const REGIONS=[{name:"usa",id:"reg_01KXT623CTGM9NJJYK2G4DQW7E"},{name:"canada",id:"reg_01KVJF9HSCYKAZC677GH1AC6C8"}]
const FIELDS=["id","title","handle","status","metadata","created_at","updated_at","deleted_at","sales_channels.id","sales_channels.name","categories.id","categories.name","collection.id","collection.title","tags.value","variants.id","variants.title","variants.metadata","variants.manage_inventory","variants.allow_backorder","variants.inventory_quantity","variants.prices.currency_code","variants.prices.amount"]
async function key(query:any){const {data}=await query.graph({entity:"api_key",fields:["token","type"],filters:{type:"publishable"}});return data?.[0]?.token}
export default async function diagnose({container}:ExecArgs){const logger=container.resolve(ContainerRegistrationKeys.LOGGER),query=container.resolve(ContainerRegistrationKeys.QUERY),token=await key(query),base=(process.env.MEDUSA_BACKEND_URL||"http://localhost:9000").replace(/\/$/,"");const {data}=await query.graph({entity:"product",fields:FIELDS});const products=(data||[]) as any[];const targets=["Organic Apples","chocolate","Organic OIL"].map(title=>products.filter(p=>p.title?.toLowerCase()===title.toLowerCase()).map(p=>({id:p.id,title:p.title,handle:p.handle,status:p.status,deletedAt:p.deleted_at||null,salesChannels:p.sales_channels||[],metadata:p.metadata||{},variants:(p.variants||[]).map((v:any)=>({id:v.id,title:v.title,cad:v.prices?.find((x:any)=>x.currency_code==="cad")?.amount??null,usd:v.prices?.find((x:any)=>x.currency_code==="usd")?.amount??null,manageInventory:v.manage_inventory,allowBackorder:v.allow_backorder}))})));
const store:any={};for(const region of REGIONS){try{const r=await fetch(`${base}/store/products?limit=200&region_id=${region.id}&fields=id,title,handle,variants.id,variants.calculated_price.*`,{headers:{"x-publishable-api-key":token}});const body:any=await r.json();store[region.name]={status:r.status,count:body.products?.length||0,products:["Organic Apples","chocolate","Organic OIL"].map(title=>{const p=(body.products||[]).find((x:any)=>x.title?.toLowerCase()===title.toLowerCase());return {title,present:Boolean(p),id:p?.id||null,calculated:p?.variants?.[0]?.calculated_price||null}})}}catch(error:any){store[region.name]={status:null,error:error?.message||String(error),products:[]}}}
logger.info("[ORGANIC_APPLES_VISIBILITY_DIAGNOSIS]");logger.info(JSON.stringify({catalog:targets,store,livePriceWrites:0,catalogWrites:0},null,2))}
