import { ExecArgs } from "@medusajs/framework/types"
import { ContainerRegistrationKeys } from "@medusajs/framework/utils"
import * as fs from "fs"
import * as path from "path"
import { parse } from "csv-parse/sync"
import { APPROVAL_STATUSES, hasUnsafeAmountSyntax, parseMajorAmount, priceForCurrency } from "./lib/merchant-regional-prices.js"

const HEADERS = ["priority","product_id","product_handle","product_title","variant_id","variant_title","current_cad_price","approved_cad_price","current_usd_price","approved_usd_price","cad_issue","usd_issue","approval_status","merchant_note"]
export async function validateRealGroceryPriceRemediation(query: any) {
  const file = path.resolve(process.cwd(),"reports","real-grocery-price-remediation.csv")
  const text = fs.readFileSync(file,"utf8").replace(/^\uFEFF/,""); const rows = parse(text,{columns:true,trim:true,skip_empty_lines:true}) as any[]
  const actualHeaders = text.split(/\r?\n/,1)[0].split(",").map((x)=>x.trim()); if (actualHeaders.join("|") !== HEADERS.join("|")) throw new Error(`Invalid grocery CSV headers: ${actualHeaders.join(",")}`)
  const summary:any={totalRows:rows.length,approvedRows:0,pendingRows:0,reviewRows:0,rejectedRows:0,invalidRows:0,duplicateVariantIds:0,staleCadRows:0,staleUsdRows:0,plannedCadCreates:0,plannedCadUpdates:0,plannedUsdCreates:0,plannedUsdUpdates:0,writesPerformed:0}; const issues:any[]=[]; const actions:any[]=[]; const seen=new Set<string>()
  for (const row of rows) { const status=String(row.approval_status||"").toLowerCase(); if(!APPROVAL_STATUSES.has(status)){issues.push({variantId:row.variant_id,reason:"invalid approval_status"});summary.invalidRows++;continue}; summary[`${status}Rows`]++; if(seen.has(row.variant_id)){summary.duplicateVariantIds++;issues.push({variantId:row.variant_id,reason:"duplicate variant_id"});continue};seen.add(row.variant_id)
    const {data}=await query.graph({entity:"product",fields:["id","variants.id","variants.prices.amount","variants.prices.currency_code"],filters:{id:row.product_id}}); const product=data?.[0],variant=product?.variants?.find((v:any)=>v.id===row.variant_id); if(!variant){issues.push({variantId:row.variant_id,reason:"product or variant missing"});summary.invalidRows++;continue}; const cad=priceForCurrency(variant,"cad"),usd=priceForCurrency(variant,"usd"); if(String(cad?.amount??"")!==String(row.current_cad_price??"")){summary.staleCadRows++;issues.push({variantId:row.variant_id,reason:"stale CAD snapshot"})}; if(String(usd?.amount??"")!==String(row.current_usd_price??"")){summary.staleUsdRows++;issues.push({variantId:row.variant_id,reason:"stale USD snapshot"})}; if(status!=="approved")continue;
    const ca=String(row.approved_cad_price||""),us=String(row.approved_usd_price||""); if(!ca&&!us){issues.push({variantId:row.variant_id,reason:"approved row has no price"});summary.invalidRows++;continue}; for(const value of [ca,us])if(value&&(hasUnsafeAmountSyntax(value)||parseMajorAmount(value)===null||parseMajorAmount(value)===0)){issues.push({variantId:row.variant_id,reason:"approved prices must be positive major-unit numbers"});summary.invalidRows++}
    const cadAction=ca?(cad?Number(cad.amount)===Number(ca)?"SKIP":"CAD_UPDATE":"CAD_CREATE"):"SKIP", usdAction=us?(usd?Number(usd.amount)===Number(us)?"SKIP":"USD_UPDATE":"USD_CREATE"):"SKIP"; if(cadAction==="CAD_CREATE")summary.plannedCadCreates++;if(cadAction==="CAD_UPDATE")summary.plannedCadUpdates++;if(usdAction==="USD_CREATE")summary.plannedUsdCreates++;if(usdAction==="USD_UPDATE")summary.plannedUsdUpdates++;actions.push({title:row.product_title,variant:row.variant_title,variantId:row.variant_id,cadAction,usdAction,beforeCad:cad?.amount??"",afterCad:ca,beforeUsd:usd?.amount??"",afterUsd:us}) }
  return {summary,issues,actions}
}
export default async function validateScript({container}:ExecArgs){const logger=container.resolve(ContainerRegistrationKeys.LOGGER),result=await validateRealGroceryPriceRemediation(container.resolve(ContainerRegistrationKeys.QUERY));logger.info("[REAL_GROCERY_PRICE_VALIDATION]");logger.info(JSON.stringify({valid:!result.issues.length,...result.summary,issues:result.issues,actions:result.actions},null,2))}
