import { calculateCommission } from "./calculate"
import type { CommissionInput } from "./calculate"

// Type representing the bucket output from split-order-workflow
export interface VendorBucketInput {
  vendor_id: string
  item_count: number
  total: number // subtotal in minor units (cents)
  items?: any[]
}

export interface VendorPayoutResult {
  vendor_id: string
  subtotal: number
  commission_amount: number
  vendor_payout: number
}

/**
 * Calculates the exact vendor commission and payout for a list of multi-vendor buckets.
 * 
 * Rules:
 * - Vendor commission is calculated separately for each vendor against their specific subtotal.
 * - Vendor commission is DEDUCTED from the vendor's subtotal to determine payout.
 * - Payout formula: vendor_payout = vendor_subtotal - vendor_commission
 * - Unlinked items (sold directly by platform) are completely ignored.
 * 
 * @param buckets - The vendor buckets generated by splitOrderWorkflow
 * @param activeVendorRule - The currently active commission rule for "vendor" (or null if none exists)
 * @returns Array of calculated payouts per vendor
 */
export function calculateMultiVendorPayouts(
  buckets: VendorBucketInput[],
  activeVendorRule: CommissionInput | null
): VendorPayoutResult[] {
  if (!buckets || buckets.length === 0) {
    return []
  }

  const results: VendorPayoutResult[] = []

  for (const bucket of buckets) {
    // If there is an active vendor rule, calculate the commission.
    // Otherwise, commission is 0.
    const commission = activeVendorRule
      ? calculateCommission(activeVendorRule, bucket.total)
      : { commission_amount: 0, vendor_payout: bucket.total }

    results.push({
      vendor_id: bucket.vendor_id,
      subtotal: bucket.total,
      commission_amount: commission.commission_amount,
      vendor_payout: commission.vendor_payout,
    })
  }

  return results
}
