export const OMS_STATUSES = [
  "PENDING", "CONFIRMED", "ALLOCATED", "PROCESSING", "READY_FOR_FULFILLMENT",
  "PARTIALLY_FULFILLED", "FULFILLED", "PARTIALLY_SHIPPED", "SHIPPED", "DELIVERED",
  "CANCEL_REQUESTED", "CANCELLED", "RETURN_REQUESTED", "PARTIALLY_RETURNED", "RETURNED",
  "REFUND_PENDING", "PARTIALLY_REFUNDED", "REFUNDED", "FAILED", "ON_HOLD",
] as const

export type OmsStatus = typeof OMS_STATUSES[number]

const transitions: Record<OmsStatus, readonly OmsStatus[]> = {
  PENDING: ["CONFIRMED", "CANCEL_REQUESTED", "CANCELLED", "FAILED", "ON_HOLD"],
  CONFIRMED: ["ALLOCATED", "PROCESSING", "READY_FOR_FULFILLMENT", "CANCEL_REQUESTED", "CANCELLED", "FAILED", "ON_HOLD"],
  ALLOCATED: ["PROCESSING", "READY_FOR_FULFILLMENT", "CANCEL_REQUESTED", "ON_HOLD"],
  PROCESSING: ["READY_FOR_FULFILLMENT", "PARTIALLY_FULFILLED", "FULFILLED", "CANCEL_REQUESTED", "ON_HOLD"],
  READY_FOR_FULFILLMENT: ["PARTIALLY_FULFILLED", "FULFILLED", "PARTIALLY_SHIPPED", "SHIPPED", "CANCEL_REQUESTED", "ON_HOLD"],
  PARTIALLY_FULFILLED: ["FULFILLED", "PARTIALLY_SHIPPED", "SHIPPED", "CANCEL_REQUESTED", "ON_HOLD"],
  FULFILLED: ["PARTIALLY_SHIPPED", "SHIPPED", "CANCEL_REQUESTED", "ON_HOLD"],
  PARTIALLY_SHIPPED: ["SHIPPED", "DELIVERED", "RETURN_REQUESTED", "ON_HOLD"],
  SHIPPED: ["DELIVERED", "RETURN_REQUESTED", "ON_HOLD"],
  DELIVERED: ["RETURN_REQUESTED", "REFUND_PENDING"],
  CANCEL_REQUESTED: ["CANCELLED", "CONFIRMED", "PROCESSING", "ON_HOLD"],
  CANCELLED: ["REFUND_PENDING", "PARTIALLY_REFUNDED", "REFUNDED"],
  RETURN_REQUESTED: ["PARTIALLY_RETURNED", "RETURNED", "DELIVERED", "ON_HOLD"],
  PARTIALLY_RETURNED: ["RETURNED", "REFUND_PENDING", "PARTIALLY_REFUNDED"],
  RETURNED: ["REFUND_PENDING", "PARTIALLY_REFUNDED", "REFUNDED"],
  REFUND_PENDING: ["PARTIALLY_REFUNDED", "REFUNDED", "ON_HOLD"],
  PARTIALLY_REFUNDED: ["REFUNDED"],
  REFUNDED: [],
  FAILED: ["PENDING", "ON_HOLD", "CANCELLED"],
  ON_HOLD: ["PENDING", "CONFIRMED", "ALLOCATED", "PROCESSING", "READY_FOR_FULFILLMENT", "CANCELLED", "FAILED"],
}

export function isOmsStatus(value: unknown): value is OmsStatus {
  return typeof value === "string" && (OMS_STATUSES as readonly string[]).includes(value)
}

export function canTransition(from: OmsStatus, to: OmsStatus): boolean {
  return from === to || transitions[from].includes(to)
}

export function assertTransition(from: string, to: string): asserts to is OmsStatus {
  if (!isOmsStatus(from) || !isOmsStatus(to) || !canTransition(from, to)) {
    const error = new Error(`Invalid OMS state transition: ${from} -> ${to}`) as Error & { status?: number }
    error.status = 409
    throw error
  }
}

export const CUSTOMER_SAFE_EVENTS = new Set([
  "ORDER_RECEIVED", "PAYMENT_CONFIRMED", "STATUS_CHANGED", "CANCEL_REQUESTED",
  "RETURN_REQUESTED", "REFUND_CREATED", "SHIPMENT_CREATED", "DELIVERED", "ORDER_ON_HOLD",
])
