import { model } from "@medusajs/framework/utils"

export const Subscription = model.define("subscription", {
  id: model.id().primaryKey(),
  customer_id: model.text(),
  customer_email: model.text(),
  idempotency_key: model.text().nullable(),
  input_fingerprint: model.text().nullable(),
  product_id: model.text().nullable(),
  product_title: model.text().nullable(),
  stripe_subscription_id: model.text().nullable(),
  stripe_customer_id: model.text().nullable(),
  stripe_payment_method_id: model.text().nullable(),
  plan: model.enum(["weekly", "monthly", "quarterly", "yearly"]).default("monthly"),
  status: model.enum(["draft", "active", "trialing", "past_due", "paused", "cancelled", "expired"]).default("draft"),
  interval_count: model.number().default(1),
  amount: model.number(),
  currency: model.text().default("usd"),
  region_id_reference: model.text().nullable(),
  sales_channel_id_reference: model.text().nullable(),
  shipping_address_snapshot: model.json().nullable(),
  billing_address_snapshot: model.json().nullable(),
  payment_provider: model.text().default("stripe_billing"),
  current_period_start: model.dateTime().nullable(),
  current_period_end: model.dateTime().nullable(),
  cancelled_at: model.dateTime().nullable(),
  paused_at: model.dateTime().nullable(),
  next_billing_date: model.dateTime().nullable(),
  trial_end: model.dateTime().nullable(),
  last_billed_at: model.dateTime().nullable(),
  failed_payment_count: model.number().default(0),
  metadata: model.json().nullable(),
})
