import { Mail, Printer, X } from "lucide-react";
import { posApi } from "../../services/posApi";

const money = (amount, currency) => new Intl.NumberFormat("en-CA", { style: "currency", currency: String(currency || "cad").toUpperCase() }).format(Number(amount || 0) / 100);

export default function POSReceipt({ receipt, transaction, onClose, onNewSale }) {
  if (!receipt) return null;
  const data = receipt.receipt_payload || receipt;
  const print = async () => { if (transaction?.id) await posApi.markReceiptPrinted(transaction.id); window.print(); };
  const email = async () => { const address = window.prompt("Receipt email address"); if (address && transaction?.id) await posApi.emailReceipt(transaction.id, address); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-md overflow-y-auto rounded bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-4"><h2 className="text-lg font-black">Receipt</h2><button onClick={onClose} className="rounded p-2 hover:bg-zinc-100"><X size={18} /></button></div><div id="pos-receipt" className="p-5 font-mono text-sm"><div className="text-center"><p className="text-lg font-black">{data.store_name || "Eatsie"}</p><p>{data.register_name}</p><p>{data.receipt_number}</p><p>Order #{data.order_display_id || data.order_id}</p><p>{new Date(data.date_time || data.date).toLocaleString()}</p></div><div className="my-4 border-y border-dashed py-3"><p>Operator: {data.operator_id || data.cashier}</p><p>Currency: {String(data.currency_code || "").toUpperCase()}</p></div>{data.items?.map((item, index) => <div key={`${item.sku || item.title}-${index}`} className="mb-3"><div className="flex justify-between gap-3"><span>{item.title}</span><span>{money(item.line_total_minor, data.currency_code)}</span></div><p className="text-xs text-zinc-500">{item.quantity} × {money(item.unit_price_minor, data.currency_code)}</p></div>)}<div className="mt-4 border-t border-dashed pt-3"><div className="flex justify-between"><span>Subtotal</span><span>{money(data.subtotal_minor, data.currency_code)}</span></div><div className="flex justify-between"><span>Discount</span><span>-{money(data.discount_total_minor, data.currency_code)}</span></div><div className="flex justify-between"><span>Tax</span><span>{money(data.tax_total_minor, data.currency_code)}</span></div><div className="mt-2 flex justify-between text-lg font-black"><span>Total</span><span>{money(data.total_minor, data.currency_code)}</span></div></div><p className="mt-5 text-xs">{data.return_policy}</p></div><div className="grid grid-cols-3 gap-2 border-t p-4"><button onClick={print} className="flex h-12 items-center justify-center gap-1 rounded border font-black"><Printer size={17} /> Print</button><button onClick={email} className="flex h-12 items-center justify-center gap-1 rounded border font-black"><Mail size={17} /> Email</button><button onClick={onNewSale} className="h-12 rounded bg-emerald-700 font-black text-white">New sale</button></div></div></div>;
}
